data = {
    arts:{
        ideas: [
            {
                title: "Dark - Screenplay Of A Scene",
                tagline: "The screenplay for a scene of the series Dark.",
                bg: "./assets/art/ideas/dark.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
            {
                title: "I2U",
                tagline: "What's Love",
                bg: "./assets/art/ideas/love.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
            {
                title: "Whenvmet",
                tagline: "When two close people met after a long time but the meeting didn't go as expected!",
                bg: "./assets/art/ideas/whenvmet.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
            {
                title: "High Way",
                tagline: "The High way of Iesh's life",
                bg: "./assets/art/ideas/highway.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
            {
                title: "Stars - I Wonder!",
                tagline: "What do stars signify & destined for?",
                bg: "./assets/art/ideas/dark.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
            {
                title: "A Second Pandora Box",
                tagline: "The portrayal of Pandora Box in a new light.",
                bg: "./assets/art/ideas/dark.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
            {
                title: "Hedonistic Egoism",
                tagline: "A plot portraying Hedonistic egoism",
                bg: "./assets/art/ideas/dark.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
            {
                title: "Thy World",
                tagline: "A Poem",
                bg: "./assets/art/ideas/dark.webp",
                details: {
                    synopsis: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus omnis impedit vel eos vero, sit est nulla, odit eveniet nisi dolor pariatur rem. Nisi consectetur saepe culpa reiciendis harum, impedit reprehenderit nostrum expedita esse possimus, repudiandae beatae rem recusandae dolorum non quaerat id autem laboriosam. Reprehenderit tempore reiciendis asperiores nostrum neque. Iusto, dolores voluptatibus tempore fuga itaque iste repudiandae provident eius eos sequi nobis totam! Repellendus laborum neque culpa in, eaque adipisci ea reiciendis iure excepturi optio veritatis ab illo rem vero laboriosam maiores provident quisquam debitis molestiae aut? Deleniti cum veritatis sunt consequatur aut, aperiam nisi dolorem laboriosam, assumenda eum nesciunt quas totam dolorum delectus illum ipsa est, recusandae doloribus id reprehenderit fugiat! Consectetur velit alias excepturi mollitia quo deserunt neque. In nemo blanditiis voluptate tempora, possimus quasi minus est ipsa repellendus reprehenderit nisi doloremque, saepe eaque et corporis neque praesentium repellat temporibus. Obcaecati dolores saepe placeat architecto ipsum nemo quod, voluptate illum quia omnis cupiditate ab id iure similique pariatur quidem totam. At magnam velit eaque error deserunt laborum incidunt, quos consectetur nesciunt ducimus omnis id assumenda doloribus facere rerum. Ut dolor, eius, mollitia et, quidem libero nemo suscipit est voluptatem ab id officiis doloremque necessitatibus ducimus minima.`,
                    treatment: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse eius vitae quos neque mollitia, hic veritatis fuga dolorum odit ipsa modi, laborum quo quae eum vel sit aliquid repellendus sed. Incidunt placeat assumenda cumque accusantium delectus perspiciatis et tempore, necessitatibus eos! Error voluptatum delectus architecto distinctio perferendis magni iusto reprehenderit?`,
                    character: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum quas cumque inventore ipsam rerum, soluta nostrum natus labore delectus tempora voluptatibus voluptate, vel quam, minima repellendus non atque ducimus. Facere, adipisci veritatis quam aliquid distinctio quia quidem fugit natus eligendi iste architecto, earum voluptates nostrum minima repellat aliquam quibusdam praesentium officia. Molestias quasi provident quaerat corporis cum, facere tempore animi nostrum amet voluptas ex praesentium earum ducimus cupiditate, deleniti soluta sapiente alias deserunt laudantium numquam dolore vero. Fugiat quidem deserunt, odit delectus tenetur alias nulla laboriosam magni distinctio debitis tempore blanditiis sed laudantium. Pariatur laborum vel, numquam quaerat quam quidem?`
                }
            },
        ],
        works: [

        ]
    }
}